version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Assurez-vous que le Dockerfile est dans le même répertoire
    image: task-app # Nom correct pour l'image
    container_name: task
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: task
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9000:9000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD: 
      MYSQL_USER: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
